const { createClient } = require("@supabase/supabase-js");

const supabase = createClient(
  "https://vwdrazlzphfgdpgskkui.supabase.co",
  "sb_publishable_zbSLxI5R5GthF-lbo3hoRQ_T1PjFiN0"
);

const entries = [
  { name: "A Story About My Uncle", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Alan Wake (non-remastered)", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Amnesia: The Dark Descent", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Ancient Enemy", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Atom Eve", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Epic Games | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Bang Bang Racing", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Prime Gaming | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Bioshock 1 & 2 Remastered", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Blade Of Darkness", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Blazblue Continuum Shift Extend", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Blood Knights", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Book Of Demons", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Borderlands 2 & The Pre-Sequel", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Braid", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Call Of Juarez: Bound In Blood", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Call Of Juarez: Gunslinger", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Capcom Arcade Stadium", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "CarmaGeddon TDR 2000", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Castlevania Anniversary Collection", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Cat Quest II", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Chainsaw Warrior", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Chicken Assassin Reloaded", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Costume Quest", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Costume Quest 2", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Cursed To Golf", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Deadly Premonition", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Death's Gambit Afterlife", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Epic Games | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Deathspank: The Baconing & Thongs Of Virtue", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Deus Ex: Human Revolution", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Diablo II", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Diggles: The Myth Of Fenris", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Dishonored: Definitive Edition", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Disney Pixar's Cars", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Prime Gaming | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Divine Divinity", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Dome Keeper", status: "working", chip: "M1 Pro", ram_gb: 16, method: "proton", notes: "Source: Steam | via u/mario2521 (r/AsahiGaming wiki)" },
  { name: "Don't Starve Together", status: "working", chip: "M1", ram_gb: 16, method: "native", notes: "Source: Steam | via u/BassedWarrior (r/AsahiGaming wiki)" },
  { name: "Double Dragon Trilogy", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Draw Slasher", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Dungeons 2", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Eschalon Book II", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "F-19 Stealth Fighter", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Factorio Demo", status: "working", chip: "M1", ram_gb: 16, method: "native", notes: "Source: Steam | via u/BassedWarrior (r/AsahiGaming wiki)" },
  { name: "Fallout 3", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Fallout Tactics", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Fallout: New Vegas", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Final Fantasy VII", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Final Fantasy VIII", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Forager", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Frozen Synapse", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Gargoyles Remastered", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Prime Gaming | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Giana Sisters: Twisted Dreams", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Prime Gaming | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Greedfall", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "GTA III", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "GTA: San Andreas", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Halo: The Master Chief Collection", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Hitman 2, Contracts & Blood Money", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Hitman: Absolution", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Hoard", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Joe Danger", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Joe Dever's Lone Wolf HD Remaster", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "King's Bounty: The Legend", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Kingdoms and Castles", status: "working", chip: "M1 Pro", ram_gb: 16, method: "proton", notes: "Source: Steam | via u/mario2521 (r/AsahiGaming wiki)" },
  { name: "Left 4 Dead", status: "partial", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Left 4 Dead 2", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Legacy Of Kain: Soul Reaver 1 & 2", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Lego Indiana Jones", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Lego The Lord Of The Rings", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Loco Motive", status: "working", chip: "M2", ram_gb: 16, method: "proton", notes: "Source: Steam | No launch option needed (Proton 9.0.4) | via u/zynlo (r/AsahiGaming wiki)" },
  { name: "Master Of Magic", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Max: The Curse Of The Brotherhood", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Prime Gaming | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Morbid: The Seven Acolytes", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Epic Games | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Mortal Kombat 4", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Need for Speed Payback", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/Shalaga44 (r/AsahiGaming wiki)" },
  { name: "Need For Speed: Most Wanted", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Neurodeck", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Nova Roma Demo (Early Access)", status: "working", chip: "M1 Pro", ram_gb: 16, method: "proton", notes: "Source: Steam | via u/mario2521 (r/AsahiGaming wiki)" },
  { name: "Oddworld: Stranger's Wrath HD", status: "partial", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Outer Wilds", status: "partial", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | via u/EclecticEman (r/AsahiGaming wiki)" },
  { name: "Overcooked", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Path of Exile 2", status: "partial", chip: "M1", ram_gb: 64, method: "proton", notes: "Source: Steam | via u/Low-Ant-756 (r/AsahiGaming wiki)" },
  { name: "PixelJunk Monsters", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Populous: The Beginning", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Portal 2", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Prince Of Persia: Sands Of Time & The Two Thrones", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "R.E.P.O.", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | via u/Shalaga44 (r/AsahiGaming wiki)" },
  { name: "Rayman 2 & 3", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Requiem: Avenging Angel", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Rocketbirds: Hardboiled Chicken", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Saints Row 2", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Shadow Warrior 2", status: "partial", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Shapez 2", status: "partial", chip: "M1", ram_gb: 16, method: "native", notes: "Source: Steam | via u/BassedWarrior (r/AsahiGaming wiki)" },
  { name: "Skydrift Infinity", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Epic Games | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Skyrim (32-bit version)", status: "partial", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "South Of The Circle", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Speedball 2 HD", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Spells & Secrets", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Spelunky", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Star Wars: Galactic Battlegrounds Saga", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Star Wars: Starfighter & Rogue Squadron", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Star Wars: X-Wing Alliance", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Star Wars: X-Wing Vs Tie Fighter", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Stardew Valley", status: "working", chip: "M1", ram_gb: 16, method: "native", notes: "Source: Steam | Multiplayer confirmed | via u/BassedWarrior (r/AsahiGaming wiki)" },
  { name: "Syberia I & II", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "System Shock 2", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "System Shock Enhanced Edition", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Team Fortress 2", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "The Chaos Engine", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "The Falconeer", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "The First Templar", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Thief: The Dark Project & The Metal Age", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "This War Of Mine", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Tomb Raider II, The Last Revelation, Chronicles, Legend & Anniversary", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Tomb Raider III & Angel Of Darkness", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Tomb Raider: Underworld", status: "partial", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Torchlight", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Trine 1 & 2", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Truck Racer", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Under The Moon", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Velocity Ultra", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Venetica", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Vessel", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Warhammer 40,000: Dawn Of War 1 & 2", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Prime Gaming | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Warhammer 40,000: Space Marine", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Prime Gaming | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Witch It!", status: "broken", chip: "M1", ram_gb: 16, method: "proton", notes: "via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Worms Crazy Golf", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Worms Reloaded", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "XCOM: Enemy Unknown", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: Steam | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
  { name: "Xenonauts", status: "working", chip: "M1", ram_gb: 16, method: "proton", notes: "Source: GOG | Launch: FEX_X87REDUCEDPRECISION=1 %command% | via u/ForgottenFoundation (r/AsahiGaming wiki)" },
];

async function main() {
  const { error } = await supabase.from("entries").insert(entries.map(e => ({ ...e, type: "game" })));
  if (error) {
    console.error("Error:", error.message);
  } else {
    console.log(`Inserted ${entries.length} entries successfully!`);
  }
}

main();
